### ISSUE TITLE
steering wheel is not recognized

### ISSUE THREAD

**Issue by qji77** [virtual-programming/dirtshowdown-linux#11]
I can't choose anything else then keyboard from the "controls" menu preset list, however my steeling wheel is connected. Without steering wheel is practically useless.

Details:
OS: Ubuntu 15.04 x64
Steering wheel: Logitech G25

**Comment by vpltd-peterm** [comment]
From googling, it seems this wheel does not work out of the box on Linux:
http://askubuntu.com/questions/281698/logitech-g25-racing-wheel

You would also have to create an SDL gamepad mapping, or use Steam's Big Picture controller set up to configure it. After that, Dirt should pick it up.

**Comment by vpltd-peterm** [comment]
Please see the front page release notes for BuildID 761021, released today for more information

**Comment by qji77** [comment]
This ltwheelconf seems more like a fine tune tools then a driver thingy. Anyway, I tried and it works, but doesn't help. I tried 'jstest-gtk' as well, which detects the steering wheel (shows the movement), but Dirt still doesn't.

I've checked in the steam client as well, which recognize the steering wheel, but seems buggy (screenshot bellow) and can't change any settings for it. I've opened a ticket for steam.

![screenshot from 2015-09-02 22 53 56](https://cloud.githubusercontent.com/assets/14099928/9694417/d3798eaa-5358-11e5-9568-58fe4797f6f9.png)

**Comment by qji77** [comment]
BTW: what is "SDL gamepad mapping"? I am happy to do it as soon as I know. :)

And I don't find the "release notes for BuildID 761021", could you please link it?

**Comment by chrisaq** [comment]
@vpltd-peterm I don't think it is enough to add wheel specifics to SDLGamepad.config, as wheels need dead zones and such set up. As it is now i have to turn the wheel 400+ degrees to turn to each side, since my wheel is a 900 degree wheel.
So what I guess is missing is making the wheel less sensitive.

Oh, and BTW, all the most known wheels are supported by the kernel now, the ltwheelconf project is dead since they got it all in the mainline kernel.

Add the following to `SteamApps/common/DiRT Showdown/SDLGamepad.config` to test:
<pre>
030000006d0400009bc2000011010000,G27 Racing Wheel,platform:Linux,a:b6,b:b7,x:b10,y:b21,back:b8,start:b11,guide:b9,leftshoulder:b20,rightshoulder:b18,leftstick:b1,rightstick:b2,leftx:a0,lefttrigger:a3,righttrigger:a2,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,
</pre>

**Comment by vpltd-peterm** [comment]
I've added that mapping for the latest build of the game.
In Dirt Showdown itself, you can find  Options & Extras -> Controls -> Advanced wheel settings. Try adjusting the wheel saturation and linearity.

**Comment by chrisaq** [comment]
@vpltd-peterm Wow thanks, that was fast, a bit TOO fast in fact :)
I mixed up the acceleration and deceleration, I added the updated config at the bottom.

Also, I can't believe I missed that wheel config menu.
It does help, but even with "Steering saturation 100%" and "Steering linearity 10"(maxed) it still lacks sensitivity (and FF of course).

I'm now looking into ways to set the wheel to 200 degrees, ltwheelconfig was supposed to be able to do this, but I haven't found a way to do this with the kernel driver yet.

<pre>
Wheel,platform:Linux,a:b6,b:b7,x:b10,y:b21,back:b8,start:b11,guide:b9,leftshoulder:b20,rightshoulder:b18,leftstick:b1,rightstick:b2,,leftx:a0,lefttrigger:a2,righttrigger:a3,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,
</pre>

**Comment by chrisaq** [comment]
The way to change logitech wheel options is to write to files in `/sys/bus/hid/drivers/logitech/<bus:id>/*`

I wrote a small script to find devices and set the range here:
https://github.com/chrisaq/lt-tools

I don't know how easily you can add these things to DS, but if you can, setting range to approximately 200 is a must for G27 and G25.

**Comment by vpltd-peterm** [comment]
Closing as bug resolved

**Comment by qji77** [comment]
It seem really the SDLGamepad.config line is missing. This G27 line didn't help for G25. Then I figured out the "ID" for G25 is 030000006d04000099c2000011010000, but I have no idea about the other arguments. I copied the G27 config line, just changed the ID (and the name), now Dirt realize the steering wheel, but as a "Controller" (so not with the correct name) and the controls are messed up.

How I could figure out the other part of this SDLGamepad.config line?

**Comment by vpltd-kgalaj** [comment]
You should be able to gather a mapping from Steam Big Picture, with the following procedure:

1. Launch Steam client.
2. Connect your steering wheel and make sure it's on.
3. Switch to Steam Big Picture, if Steam Client is not in Big Picture mode (it's an icon depicting a gamepad in the top right corner of Steam window).
4. When Steam's Big Picture menu shows up, navigate to Settings (it's an icon near the 'exit' one in top right corner of the screen.
5. Select 'Controller' option.
6. At this point you should see your steering wheel mappings. Make sure that they're all as you want them in the game, and then select 'Save' option.
7. Steam may ask you to share your mapping with others at this point - agree or decline, it shouldn't matter.
8. Exit Steam.
9. List contents of '~/.local/shared/Steam/config.vdf' file, near the end of the file there should be a line starting with "SDL_GamepadBind". The rest of the line would be a jumble of letters and numbers looking a bit like this (example): "5e040000000000008e02000000000000,Wireless 360 Controller,a:b0,b:b1,y:b3,x:b2,start:b10,guide:b8,back:b9,leftstick:b6,rightstick:b7,leftshoulder:b4,rightshoulder:b5,dpup:b11,dpleft:b13,dpdown:b12,dpright:b14,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,".
10. If there is such a line, the exact text between quotation marks in the rest of the line, excluding the quotation marks, is your mapping. Copy it somewhere.
11. If there is no such line in the file, go back to step 1, and get through steps, changing something in controller mappings in step 6, and select Save again to force Steam to save the mapping. Then get through remaining steps, list the config.vdf file again, and look for the controller mapping again, until you have it.
12. Append the mapping to SDLGamepad.config file to get the game to recognise it.
