### ISSUE TITLE
Transparent/missing tires.

### ISSUE THREAD

**Issue by shadowflash** [virtual-programming/dirtshowdown-linux#19]
![2015-11-06_00005](https://cloud.githubusercontent.com/assets/3712854/10997497/aa0ccd6c-849e-11e5-9dde-a0f41ce2252e.jpg)

This is how the tires of your own and sometimes rival car looks like.
It happens on 2 machines (x86 and x86_64) with Ubuntu 14.04, Phenom II x4 955BE, Geforce GT 440 and Quadro 6000 (system specs are almost identical with the only difference in RAM size - 16 and 32GB and video cards - GT440 and Quadro 6000) Both have latest nvidia drivers installed and everything is the same except resolution (1024x768 on machine with GT440 and 1920x1080 on machine with Quadro ). When you see a car before racing all tires look normal but in the actual race they look like on the screenshot.

**Comment by scrawl** [comment]
Duplicate of #4?

**Comment by shadowflash** [comment]
Yeah, sorry, missed it.
