### ISSUE TITLE
Infinite loading after beat Ken Block (head 2 head) on Showdown Tour PRO

### ISSUE THREAD

**Issue by VelhoP** [virtual-programming/dirtshowdown-linux#2]
Controls still work.
Alt + tab works.
It just keep on loading screen.

Hardware:
Core i7 870
GTX 970
16GB RAM

Software:
Linux Mint 17.2
Kernel 4.1.6
NVIDIA 355.06

**Comment by vpltd-peterm** [comment]
Was this repeatable ? or a one time event ?
If it's repeatable, please attach your eon.txt for us to look at

**Comment by VelhoP** [comment]
Yep, repeatable.
Can't get my gold medal. =|

Hum it generated a 2,0MB eon.txt
I think its not good idea to paste such a big text here.
Can i send it by email?

**Comment by vpltd-peterm** [comment]
Use Gist for this

**Comment by VelhoP** [comment]
It is a little bigger now.

186.752 lines.

https://gist.github.com/VelhoP/4d480e240c5294e19574#file-eon-txt

**Comment by xpander69** [comment]
it happened for me also once. during an online game with my friend.. after we finished racing he alt+f4 out of the game when it was showing the results and i as a hoster was stuck in infinite loading screen after this.

minor issue imo.
havent seen this happening on other cases

**Comment by vpltd-kgalaj** [comment]
It's the hang GaminOnLinux mentiones in the review, which we're still working on catching, hence the need for eon.txt files. We're interested also in records of one-time events, not only repeatable ones.

eon.txt file you sent doesn't show a prolonged hang on loading screen. Are you sure it's the version of the file from the run you had the issue on? It gets recreated and overwritten on every game launch, so if you relaunched the game before sending eon.txt file, the hang information would have been lost.

**Comment by xpander69** [comment]
sadly i dont have log from that 1 hang i got
will keep my eyes open though.. if that happens next time i try to make a backup of the log file and post here

**Comment by stqn1** [comment]
This bug also happened several times for me, after various races. Usually when I alt-f4 then restart the game, it doesn’t get stuck. It seems random.

Gentoo 64 bit, Core i5 4690K, GTX 660 2GB, nvidia 352.30.

eon.txt: https://gist.github.com/stqn1/368c84ba45d862832593

(I launched the game, went directly to the latest unlocked race, played the two races, then it got stuck on the loading screen and I pressed alt-f4.)

**Comment by vpltd-kgalaj** [comment]
Thank you for the log. That does give me the full picture of the issue, though doesn't yet point to the solution. Basically, a job has been issued to worker thread set, but no worker thread has chosen to pick it up, despite there being free worker threads around. This might be a https://en.wikipedia.org/wiki/Priority_inversion issue, though that's unlikely, given that we're not messing with thread priorities at all on Linux, giving all threads same default priority, or it might be some race condition making the EGO engine worker thread set unsafe, as there have been reports of the game not progressing past loading screens on Windows as well. We'll review the code thoroughly.

**Comment by stqn1** [comment]
Not sure if it’s the same bug, but now Dirt is stuck on a black screen at the very start, before it shows any logo.
First try (I could alt-f4 out of the game): https://gist.github.com/stqn1/0f35112af9b2e6cacf1f
Second try (game was completely stuck, I had to pkill -9 E.runloop): https://gist.github.com/stqn1/fe3a4af40fc6148bdca2

If it matters, I’m using the intel_pstate scaling driver with its "performance" governor, on the Linux 4.0.5 kernel.

**Comment by vpltd-kgalaj** [comment]
It appears to be a different bug, or bugs. Unfortunately, there are no hints as to why they could be happening in eon.txt logs.

Possibly it might matter - as the issue doesn't appear to be widespread, non-standard elements of OS configurations become first suspects.

**Comment by vpltd-kgalaj** [comment]
I outlined potential solution, that you can check to see if it fixes the issue on your machine, in issue #7  .

**Comment by VelhoP** [comment]
Now when I beat him in the race, can not advance to the next race.
When i check NEXT after i win, its like i hit RESTART.
BUT, if i lose, i can go to next race...
It happened after this latest patch.
Log: https://gist.github.com/VelhoP/d03682c91db4330f325f

**Comment by vpltd-kgalaj** [comment]
So, before last patch, it was possible to beat Ken Block, and the game progressed normally, and this behaviour started only after last patch? Does it happen for anyone else? Please advise. I see nothing incorrect in the logs, and we're using the same data and same code as the original game, and there is no information about such problem in the original game, so at the moment I have to assume it's something with specific game installation.

**Comment by VelhoP** [comment]
Before the patch, after beating him I was stuck on the loading screen.  
Now when I beat him, I can not advance.  
I just checked game integrity on steam, nothing wrong with it.  
Hard to believe it is something with my installation...  
Don't know if it happens to everyone. But it is very easy to know.  
Go beat him?

**Comment by VelhoP** [comment]
After that last 7,8 MB patch, I got my gold medal.
Thanks!
