### ISSUE TITLE
Selected Keys Don't Show in Options Editor

### ISSUE THREAD

**Issue by d10sfan** [virtual-programming/dirtshowdown-linux#3]
This is related to the steam thread I started here (http://steamcommunity.com/app/201700/discussions/0/530649887216902365/) 

Basically, the control editor works, except that the keys never show up (they are just blank) and the shift key is not selectable.

**Comment by xpander69** [comment]
confirming. letter keys dont show up, spacebar, ctrl and arrow keys show.
they are all bindable and working though but just cant see them

and yeah shift is not bindable also

**Comment by vpltd-peterm** [comment]
There should soon be an update, BuildID 750604, and this problem should be fixed

**Comment by dnimon** [comment]
Great thanks for the response. Just tried it out and the keys showed up correctly now, but the Shift key is not assignable.

**Comment by d10sfan** [comment]
Great thanks for the response. Just tried it out and the keys showed up correctly now, but the Shift key is not assignable.

**Comment by vpltd-kgalaj** [comment]
Shift key bug hasn't yet been fixed, but it will be.

**Comment by vpltd-peterm** [comment]
Please check this with the latest update, BuildID 757342

**Comment by vpltd-peterm** [comment]
Closing as issue is confirmed fixed
