### ISSUE TITLE
Steam Freeze when quitting DIRT then all desktop freeze when unplugging gamepad

### ISSUE THREAD

**Issue by Narann** [virtual-programming/dirtshowdown-linux#30]
Repro step:

* Play to Dirt
* Quit

Steam UI now freeze (no refresh). Two choice:
* If I quit Steam (using task bar menu "Exit Steam") the whole system freeze (no TTY etc...)
* If I unplug my gamepad, the whole system freeze (no TTY etc...).

Gamepad: Logitech Gamepad F310 (in "X" mode).
Kernel: 4.2.0-25
Distro: Linux Mitn 17.3

I dig a little to find some infos about steam freeze and it seems to be related to `xpad` driver. While my gamepad don't support vibration, I've enabled it in DIRT UI (because I have another gamepad I didn't tried yet but supporting vibration, what ever...). I will try to disable vibration from DIRT UI to see if there is some changes.

I suspect steam is waiting some gamepad stuff. If there is anything I could do just tell me. I will try to `gdb` steam and reprod the problem. :)

**Comment by vpltd-kgalaj** [comment]
Unfortunately we have no information about the internal workings of Steam, so I don't think there's anything that we could tell you that would resolve the issue. We 're using evdev to enumerate gamepads, and to get their control values, and for vibration.

**Comment by Narann** [comment]
Ok thanks. :)
