### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Senneistheboss** [virtual-programming/dirtshowdown-linux#32]
Hey 
I upgraded my pc to windows 10 and i wanted to play Dirt showndown 
But when i start it it does nothing and i go to D:\game\SteamGames\steamapps\common\DiRT Showdown
There gives me this showdown_avx_738098_crash_2016_6_1T11_20_51C0.mdmp
I already tried to install openall but doesent work pls help
-Senne

**Comment by vpltd-peterm** [comment]
Sorry, this is not a support site for the Windows version of the game.

**Comment by Senneistheboss** [comment]
Where is n Windows Game version
