### ISSUE TITLE
xbox 360 controller is not detected

### ISSUE THREAD

**Issue by subiol** [virtual-programming/dirtshowdown-linux#40]
As the title says, the xbox 360 controller is not being detected, I do not even get the option to chose it. I am using the same controller in other linux games without a problem and I have used the same controller on dirtshowdown on windows. But on linux the controller is not detected.

I am running Ubuntu 16.10. Please tell me what logs you need and I will provide them.

**Comment by vpltd-kgalaj** [comment]
The first log to check would be eon.txt file in game's data folder, probably in ~/.local/shared/Dirt , or similarly named. If a gamepad is detected, it'll be noted, if it isn't, it'll also we noted along with the detection step on which it failed.

You might also be interested in reading through this issue page, as the procedure of getting the game to detect any gamepad it wasn't previously detecting is described there at length: https://github.com/virtual-programming/dirtshowdown-linux/issues/38

**Comment by subiol** [comment]
The eon.txt file is in ~/.local/shared/vpltd/dirt. It mentions the word gamepad in this line:

> [thread 00000001][I][245]: Gamepads: registered gamepad mapping for device GUID 03000000de280000fc11000001000000

The line gets repeated with a different GUID number like about 30 times. So it seems it gets detected but once inside the game I do not get the option to chose it. I know the gamepad and my linux configuration works because the gamepad works in other linux games.

I have also read the link you provided and let me add that my controller is a wireless Xbox 360, which is the example you use in that issue as a controller that is mapped.

What should be the next step? Is it detected with some error or is it a problem of lack of configuration?

**Comment by vpltd-kgalaj** [comment]
In case of gamepad that's really passing all detection stages, it should be also enumerating its controls. Since it apparently isn't doing so, it's probably not getting detected, failing at specific stage. If I could see the whole log, I could tell more about it, as then I could compare specific logs with specific lines in source code.

**Comment by subiol** [comment]
This is the full eon.txt file

[eon.txt](https://github.com/virtual-programming/dirtshowdown-linux/files/795963/eon.txt)

**Comment by vpltd-kgalaj** [comment]
Since our game has support for several XBox 360 gamepads, it would be unlikely for it not to have support for yours at all.

The entry you mention denotes that a gamepad mapping was added to the list of known devices. It says nothing about actual gamepads on the system, only about those in our gamepad database.

After adding the gamepads, we initialize udev, and enumerate all input devices in the system. For each device, when it's detected, udev calls our function, and then we proceed to detect the device. There was no logs from device detection in the system, which means that udev was initialised, scan was made, and udev reported no gamepads to game at all, so no further detection could be done.

**Comment by subiol** [comment]
My gamepad is the official Microsoft Xbox 360 gamepad and the wireless pc adapter is Microsoft official as well. I am running Ubuntu 16.10 with the only notable modification being a ppa with the latests Mesa (which I am guessing should not interfere). And the gamepad works in other linux games.

What should be the next step to solve the problem?

**Comment by subiol** [comment]
Ok, so I remembered the last time I launched dirt showdown the gamepad was off, so I have launched the game again this time with the gamepad on and these lines have appeared now under the list of gamepads loaded:

>[thread 00000001][I][327]: Gamepads: New potential device at device file '/dev/input/event19'
>[thread 00000001][I][327]: Gamepads:     New potential device under path '/dev/input/event19' is 'Xbox 360 Wireless Receiver (XBOX)'
>[thread 00000001][I][327]: Gamepads:     Device GUID calculated as: 030000005e0400009102000014010000
>[thread 00000001][I][327]: Gamepads:     Device 'Xbox 360 Wireless Receiver (XBOX)' reports supporting FF_RUMBLE force feedback effect
>[thread 00000001][I][351]: Gamepads: New device added to gamepads list.
>[thread 00000001][I][351]: Gamepads: New potential device at device file '/dev/input/js0'
>[thread 00000001][I][407]: Gamepads:     New potential device rejected, couldn't get device name for device under path '/dev/input/js0'

**Comment by vpltd-kgalaj** [comment]
These lines say that the gamepad was detected, configured and is available in game. The js0 device is irrelevant.

Possibly you need to redefine gamepad controls in game in its options to assign game actions to gamepad controls?

**Comment by subiol** [comment]
So maybe I am just being obtuse but I have not found the way to select the xbox controller. When the game starts and says press start or enter, I try to hit any key of the controller and nothing works. I can only go forward by pressing Enter in the keyboard. Then I go to "options & extras" -> "controls". There I try to select a different preset but the only option available is keyboard. I have even tried to reassign the controls individually to the gamepad, but the presses do not get registered.

**Comment by subiol** [comment]
When I go into the controls menu, this appears in the eon.txt file:

>[thread 00000004][W][3017]: eON_LoadLibraryEx() couldn't load 'atiadlxx.dll', returning NULL!
>[thread 00000004][W][3017]: eON_LoadLibraryEx() couldn't load 'atiadlxy.dll', returning NULL!
>[thread 00000004][I][3026]: OutputDebugString: 0002.643 
>[thread 00000004][I][3026]: OutputDebugString: [SYSTEM] 
>[thread 00000004][I][3026]: OutputDebugString: Gaining focus
>[thread 00000004][W][3026]: Asked for NULL HGDIOBJ properties. Returning 0, but it's not ok.
>[thread 00000004][I][6513]: Raw Input: keyboard device wanted, legacy messages: on
>[thread 00000004][W][6513]: REGISTRY OPERATION: RegOpenKeyExW() returns ERROR_NOT_FOUND (subkey not found) key = HKEY_CURRENT_USER, subkey = Software\NaturalPoint\NATURALPOINT\NPClient Location
>[thread 0000003a][E][6513]: Gamepads: Device couldn't be activated, because no SDL mapping for device GUID 030000005e0400009102000014010000 has been found!
>[thread 0000003a][I][6513]: Gamepads:     To activate the device, please provide the appropriate mapping in SDL2 format through command-line ( --eon_gamepad_mapping= option ),
>[thread 0000003a][I][6513]: Gamepads:     SDL_GAMECONTROLLERCONFIG environment variable, or SDLGamepad.config file, located in game data folder.
>[thread 0000003a][I][6513]: Gamepads:     SDL2 format mapping strings can be determined using Steam Big Picture configurator.
>[thread 00000004][W][6513]: eON_LoadLibraryEx() couldn't load 'Error\NPClient.dll', returning NULL!
>[thread 00000004][E][6899]: Make sure that disabling screensaver by simulating non-move mouse event from time to time works. This error will be reported only once per run.

**Comment by vpltd-kgalaj** [comment]
In this case, it's exactly the same case as described in my very first reply - there is no mapping for your controller in the database, and one needs to be added as described in the link I quoted there.

**Comment by subiol** [comment]
Ok, so I finally got it working. This is the two lines I had to include to the SDLGamepad.config of the steam/dirt folder:

030000005e0400009102000014010000,xbox 360 wireless,a:b0,b:b1,y:b3,x:b2,start:b7,guide:b8,back:b6,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:b13,dpleft:b11,dpdown:b14,dpright:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,

In case you want to add them to your predefined mappings.
